### ISSUE TITLE
Validating keys passed to .with

### ISSUE THREAD

**Issue by th3james** [tcrayford/Values#18]
I notice that although `.new` validates the presence of all arguments, `.with` doesn't validate that all keys are provided (and defaults the attributes to nil). Is this intended behaviour? Is there are reason this is preferable? Seems like it would be easy to be tripped up by not specifying a value to `.with`.

If this behaviour is desirable, I'm happy to submit a PR

**Comment by tcrayford** [comment]
This isn't intended, and I'd love a PR
