### ISSUE TITLE
Please register for Codecov.io and enable this repo

### ISSUE THREAD

**Issue by ms-ati** [tcrayford/Values#29]
Hi @tcrayford,

Just like the issue for Travis CI, I just need you to sign up and enable this repo so that I can add the configuration and the badge.

https://codecov.io/

Thanks,
-Marc

**Comment by tcrayford** [comment]
Hi Marc,

Is there any particular reason you want a code coverage badge on Values? I'm not too concerned with it - it's one tiny class, and I'm not anticipating changing it a lot in the future.

**Comment by ms-ati** [comment]
Understood. Actually, there is a specific reason. When I envision adding alternate method-generating code paths (for `.with` and `#with`, for example) for Ruby 2.2+ and previous, I thought code-coverage plugin would be an excellent way to ensure we maintain coverage of both paths on all applicable Ruby versions.

Also, it is very easy to setup -- not much effort. Does that reasoning resonate with you? If not, I'm open to whatever your thinking is.

**Comment by tcrayford** [comment]
@ms-ati that makes sense. I'll take a look.

**Comment by ms-ati** [comment]
Thanks for merging my commits from yesterday ;)
Any progress on this?

**Comment by ms-ati** [comment]
@tcrayford ping

**Comment by ms-ati** [comment]
Any news on this?

**Comment by tcrayford** [comment]
Hi Marc,

I just registered, and think it's active now.

**Comment by ms-ati** [comment]
Yes, it's all set :) thanks, will close
