### ISSUE TITLE
Attributes are mutable when using mutating method

### ISSUE THREAD

**Issue by dbachet** [tcrayford/Values#52]
Hi,

Here is an example of "mutability" over the attributes.

```ruby
[1] pry(main)> X = Value.new(:x)
=> X
[2] pry(main)> x = X.new(%w[1 2 3])
=> #<X x=["1", "2", "3"]>
[3] pry(main)> x.x.concat %w[4 5 6]
=> ["1", "2", "3", "4", "5", "6"]
[4] pry(main)> x.x
=> ["1", "2", "3", "4", "5", "6"]
```
**[EDIT] replaced ValueObject by Value in code snippet**

Not sure this is wanted but it might be confusing as we could think that the library would take care of such case.

What do you think?

cc @ignacykasperowicz @mpapis

**Comment by tcrayford** [comment]
@dbachet Values *could* freeze all the things you give it, but I think that's kind of overreaching, so the current behaviour is ok.

**Comment by ms-ati** [comment]
I agree with @tcrayford (in case anyone was wondering) ;)
