### ISSUE TITLE
Update method[s]?

### ISSUE THREAD

**Issue by gfredericks** [tcrayford/Values#61]
Would it be good to have a method that lets you provide a block to "modify" a particular attribute (returning a copy of course)?

E.g., either `my_thing.update(:attr1){|attr1| ...}` or `my_thing.with(:attr1){|attr1|...}` or maybe somehow a special method for each attribute?

**Comment by tom-pang** [comment]
hello grr

That sounds nice. However, as far as I am concerned, `Value` is finished, and I am not interested in adding any new functionality at this time.

**Comment by gfredericks** [comment]
cool, thanks
